### ISSUE TITLE
Limited tabbing through fields

### ISSUE THREAD

**Issue by turban** [dhis2/maintenance-app#100]
I'm using tab on the keyboard to switch between input fields. It works for the first four fields, but then the focus leaves the form. 

![screen shot 2016-04-13 at 12 05 33](https://cloud.githubusercontent.com/assets/548708/14489919/1148ea58-0170-11e6-9207-f567d2ebe648.png)

**Comment by Markionium** [comment]
This is a larger issue that needs to be addressed. Possibily in the `<FormBuilder />` component in d2-ui.

It seems to tab through text fields, but not correctly go to custom elements like DateFields. 

Also this relates to more keyboard shortcuts like using keys for dropdowns to locate/select values.

**Comment by nicolayr** [comment]
I have the same issue in the settings app: Text fields and checkboxes get focussed correctly, but dropdown fields do not.

I'm fairly confident it's caused by material-ui, because:
- The issue occurs on their demo as well: http://www.material-ui.com/#/components/select-field
- There are several open issues related to this on material-ui. For example:
  - https://github.com/callemall/material-ui/issues/3008
  - https://github.com/callemall/material-ui/issues/3919
  - https://github.com/callemall/material-ui/issues/1644
  - (probably others)
