### ISSUE TITLE
Org units: Add data set and org unit group selector to add and edit forms

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/maintenance-app#162]
Add data sets and organisation unit groups selectors to add and edit org unit forms.

**Comment by ceciliapersson** [comment]
Data sets seem to have been available also in Organisation unit group create new form, at least it's documented in the user doc.

**Comment by ceciliapersson** [comment]
Hi,
Will this issue be fixed for 2.24?

**Comment by Markionium** [comment]
You mean as boxes like the multi select? Where you move items from one side to another?

I'm not sure if this will be fixed for 2.24. I'll do some testing to see if it is as straightforward as I hope it to be.

**Comment by ceciliapersson** [comment]
I don't recall the proposed layout for this, please verify with Lars.

If the box option can't be implemented, how do you do the following?
- Assign the org unit to a data set? (Only from the data set part of the Maintenance app?)
- Assign the org unit to an org unit group?

These functions are described in the existing user documentation. Maybe these functions have been removed from the new version of DHIS 2?

**Comment by Markionium** [comment]
Assigning an org unit to an org unit group can be done though the org unit group part of the maintenance app. 

If both of those need to be updated from both directions I'm not sure. (Not sure it is curre

**Comment by larshelge** [comment]
This is causing chaos now as in countries, the districts were allowed to assign data sets to org units themselves (distributed management). They are not given access to the data set module, just the org unit part, so this is required to support distributed management of data set assignments.

**Comment by ceciliapersson** [comment]
@Markionium @larshelge Could one of you demo the changes so I can document them? Thanks.

**Comment by ceciliapersson** [comment]
@Markionium @larshelge Could you do a demo of this functionality sometime this week?

**Comment by Markionium** [comment]
@ceciliapersson This is not yet implemented.

**Comment by ceciliapersson** [comment]
@Markionium Thanks for the info. I have it on my task list for 2.25. Do you think the functionality will be included in this release?

**Comment by davidoh** [comment]
Hi all,

Will this also solve the scalability issue that I posted to the dhis2-devs mailing list (copied below)?

**The problem**
- The number of organisationUnits (DHIS2 demo has ~2000) usually far outnumbers the number of dataSets (DHIS2 demo has ~20).
- When you assign an organisationUnit to a dataSet, the lastUpdated timestamp is only updated on the dataSet, not the organisationUnit.
- This means that when we modify one of the 2000 organisationUnits to have an additional dataSet, we are not able to use the lastUpdated filter to download the aforementioned organisationUnit including its associated dataSet IDs. We are only able to use the lastUpdated filter to download the updated dataSet along with the organisationUnit IDs of all the other (potentially up to 2000) organisationUnits already assigned to the dataSet. The organisationUnit IDs make up ~85% of the dataSets payload on the DHIS2 demo.
- Since organisationUnits are far greater in number they are more likely to be created or modified on a more frequent basis. If those modifications include dataSet assignments, then the dataSets will be "updated" each time and downloaded repeatedly.
- The payloads are still relatively small for moderate internet connections. With gzip compression, downloading all dataSets is approximately 80KB. However for poor internet connections in remote locations an 80KB payload can be problematic especially if it occurs on a recurring basis.

**Potential solution in line with this GitHub issue**
Update the lastUpdated timestamp of either the dataSet or the organisationUnit, depending upon the API resource or edit form used. In the DHIS2 demo you are able to assign/remove organisationUnits to/from dataSets using POST/DELETE requests to either /api/dataSets/\<id\>/organisationUnits/\<id\> or /api/organisationUnits/\<id\>/dataSets/\<id\>.

If you use the former (the dataSets API resource or form) then update the timestamp on the dataSet, whereas if you use the latter (the organisationUnits API resource or form) then update the timestamp on the organisationUnit.

This has the advantage of solving the issue of downloading dataSets repeatedly whilst also not introducing backwards compatibility issues for consumers of the dataSets API.

**Comment by ceciliapersson** [comment]
Data set functionality documented:
https://ci.dhis2.org/docs/master/en/user/html/manage_org_unit.html#create_org_unit
